package com.project.analyzer.telemetry.analysis.api.model.report.corner

import com.project.analyzer.telemetry.analysis.api.model.handling.SessionAnalysisHandlingState

public data class EnhancedCornerAnalysis(
    val cornerNumber: Int = 0,
    val cornerName: String = "",
    val cornerType: CornerType = CornerType.LOW_SPEED,
    val entrySpeed: Float = 0f,
    val referenceEntrySpeed: Float = 0f,
    val brakePointPosition: Float = 0f,
    val referenceBrakePoint: Float = 0f,
    val brakePointDelta: Float = 0f,
    val peakBrake: Float = 0f,
    val trailBrakingDistance: Float = 0f,
    val trailBrakingIntensity: Float = 0f,
    val apexSpeed: Float = 0f,
    val referenceApexSpeed: Float = 0f,
    val apexPosition: Float = 0f,
    val referenceApexPosition: Float = 0f,
    val apexClassification: ApexClassification = ApexClassification.OPTIMAL,
    val minSpeed: Float = 0f,
    val lateralG: Float = 0f,
    val exitSpeed: Float = 0f,
    val referenceExitSpeed: Float = 0f,
    val throttlePickupPoint: Float = 0f,
    val referenceThrottlePickup: Float = 0f,
    val throttleSmoothness: Float = 1f,
    val wheelSpinDetected: Boolean = false,
    val wheelSpinDuration: Long = 0L,
    val cornerTime: Long = 0L,
    val referenceCornerTime: Long = 0L,
    val timeDelta: Long = 0L,
    val cornerScore: Int = 0,
    val understeerRatio: Float = 0f,
    val oversteerRatio: Float = 0f,
    val handlingState: SessionAnalysisHandlingState = SessionAnalysisHandlingState.Neutral,
    val slipAngle: Float = 0f,
    val lapCount: Int = 0,
    val speedStdDev: Float = 0f,
    val consistencyScore: Int = 0,
    val primaryIssue: CornerIssue? = null,
    val recommendation: String? = null,
    val setupSuggestion: String? = null,
)
