package com.project.analyzer.ui.modifier

public object TestTags {

    public const val SegmentSeparator: String = "."
    public const val WhitespaceReplacement: String = "-"
    public const val VisibilityName: String = "AppScrollbarVisible"
    public val App: UiTestTag = uiTestTagOf("app")
    public val Test: UiTestTag = uiTestTagOf("test")
    public val Slider: UiTestTag = uiTestTagOf("slider")
    public val Button: UiTestTag = uiTestTagOf("button")
    public val CalibrationDirection: UiTestTag = uiTestTagOf("calibration", "direction")
    public val CalibrationGateDebug: UiTestTag = uiTestTagOf("calibration", "gate-debug")
    public val CalibrationScreen: UiTestTag = uiTestTagOf("calibration-screen")
    public val CalibrationSavedVerify: UiTestTag = uiTestTagOf("calibration", "saved-verify")
    public val CalibrationVerifyLastSaved: UiTestTag = uiTestTagOf("calibration", "verify-last-saved")
    public val CrashScreen: UiTestTag = uiTestTagOf("crash-screen")
    public val DevHudSettings: UiTestTag = uiTestTagOf("dev-hud-settings")
    public val DevSettingsEntry: UiTestTag = uiTestTagOf("settings", "dev-entry")
    public val CloseBehaviorSettings: UiTestTag = uiTestTagOf("settings", "close-behavior")
    public val Dropdown: UiTestTag = uiTestTagOf("dropdown")
    public val DraggableHud: UiTestTag = uiTestTagOf("draggable-hud")
    public val FileChooser: UiTestTag = uiTestTagOf("file-chooser")
    public val FuelHud: UiTestTag = uiTestTagOf("fuel-hud")
    public val HudPanelSurface: UiTestTag = uiTestTagOf("hud-panel-surface")
    public val HudSettings: UiTestTag = uiTestTagOf("hud-settings")
    public val HudSetupSettings: UiTestTag = uiTestTagOf("settings", "hud-setup")
    public val InfoBar: UiTestTag = uiTestTagOf("info-bar")
    public val InputsHud: UiTestTag = uiTestTagOf("inputs-hud")
    public val LiveScreen: UiTestTag = uiTestTagOf("live-screen")
    public val NavigationGraph: UiTestTag = uiTestTagOf("navigation-graph")
    public val NavigationLocal: UiTestTag = uiTestTagOf("navigation-local")
    public val Pagination: UiTestTag = uiTestTagOf("pagination")
    public val PagedTable: UiTestTag = uiTestTagOf("paged-table")
    public val PanelCard: UiTestTag = uiTestTagOf("panel-card")
    public val ResponsiveScreen: UiTestTag = uiTestTagOf("responsive-screen")
    public val ScreenLayout: UiTestTag = uiTestTagOf("screen-layout")
    public val SessionDetails: UiTestTag = uiTestTagOf("session-details")
    public val SessionList: UiTestTag = uiTestTagOf("session-list")
    public val ScrollbarVertical: UiTestTag = uiTestTagOf("scrollbar", "vertical")
    public val ScrollbarHorizontal: UiTestTag = uiTestTagOf("scrollbar", "horizontal")
    public val SessionStatCard: UiTestTag = uiTestTagOf("session-stat-card")
    public val SetupScreen: UiTestTag = uiTestTagOf("setup-screen")
    public val StatsRow: UiTestTag = uiTestTagOf("stats-row")
    public val TelemetryAcquisition: UiTestTag = uiTestTagOf("settings", "telemetry-acquisition")
    public val TelemetryGameSelection: UiTestTag = uiTestTagOf("settings", "telemetry-game-selection")
    public val TelemetryInspector: UiTestTag = uiTestTagOf("telemetry-inspector")
    public val TextField: UiTestTag = uiTestTagOf("text-field")
    public val TextFieldInput: UiTestTag = TextField.child("input")
    public val Theme: UiTestTag = uiTestTagOf("theme")
    public val Tooltip: UiTestTag = uiTestTagOf("tooltip")
    public val TrackMap: UiTestTag = uiTestTagOf("track-map")
    public val TrackMapBuilder: UiTestTag = uiTestTagOf("track-map-builder")
    public val TrackMapBuilderScroll: UiTestTag = TrackMapBuilder.child("scroll")
    public val TrackMapBuilderStart: UiTestTag = TrackMapBuilder.child("start")
    public val TrackMapEditorSidebar: UiTestTag = uiTestTagOf("track-map-editor", "sidebar")
    public val TrackMapLibrary: UiTestTag = uiTestTagOf("track-map-library")
    public val TrackMapPreview: UiTestTag = uiTestTagOf("track-map-preview")
    public val AppearanceSettings: UiTestTag = uiTestTagOf("settings", "appearance")

    public val Content: UiTestTag = App.child("content")
    public val Sidebar: UiTestTag = App.child("sidebar")
}
