package com.project.analyzer.telemetry.analysis.api.model.highlight
public enum class SessionAnalysisHighlightCategory {
    TopSpeed,
    ThrottleCommitment,
    BrakePoint,
    TimeLoss,
    Understeer,
    Oversteer,
    TyreOverheat,
    TyreCold,
    TrailBrakingMissing,
    EarlyApexEntry,
    LateApexEntry,
    CoastingZone,
    WheelLockup,
    WheelSpin,
    InconsistentLine,
    SetupUndersteer,
    SetupOversteer,
    TyrePressureImbalance,
    TyreTempImbalance,
    BrakeBalance,
    AeroBalance,
    DamperIssue,
}
