package com.project.analyzer.telemetry.lmu.api.model

import com.project.analyzer.math.Vec3

public data class LmuVehicleScoring(
    val id: Int,
    val driverName: String,
    val vehicleName: String,
    val totalLaps: Int,
    val sector: Int,
    val finishStatus: Int,
    val lapDist: Double,
    val pathLateral: Double,
    val trackEdge: Double,
    val bestSector1: Double,
    val bestSector2: Double,
    val bestLapTime: Double,
    val lastSector1: Double,
    val lastSector2: Double,
    val lastLapTime: Double,
    val curSector1: Double,
    val curSector2: Double,
    val numPitstops: Int,
    val numPenalties: Int,
    val isPlayer: Boolean,
    val control: Int,
    val inPits: Boolean,
    val place: Int,
    val vehClass: String,
    val timeBehindNext: Double,
    val lapsBehindNext: Int,
    val timeBehindLeader: Double,
    val lapsBehindLeader: Int,
    val lapStartEt: Double,
    val pos: Vec3,
    val localVel: Vec3,
    val localAccel: Vec3,
    val ori: List<Vec3>,
    val localRot: Vec3,
    val localRotAccel: Vec3,
    val headlights: Int,
    val pitState: Int,
    val serverScored: Int,
    val individualPhase: Int,
    val qualification: Int,
    val timeBehindFastest: Double,
    val lapsBehindFastest: Int,
    val timeBehindRisk: Double,
    val lapsBehindRisk: Int,
    val isGhost: Boolean,
    val numDuplicates: Int,
    val safetyCarInstruction: Int,
    val safetyCarPrivateInstruction: Int,
    val pitLaneStartDist: Double,
    val pitLaneEndDist: Double,
    val maxSpeed: Double,
    val vehicleFileName: String,
    val expansion: ByteArray
)
