package com.project.analyzer.kmp

import org.gradle.api.Project
import org.gradle.kotlin.dsl.configure
import org.gradle.kotlin.dsl.withType
import org.jetbrains.kotlin.gradle.dsl.KotlinMultiplatformExtension
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile
import java.util.Locale

internal fun Project.configureDesktopBuildConfig(
    block: DesktopBuildConfigSpec.() -> Unit
) {
    val spec = DesktopBuildConfigSpec().apply(block)
    val buildType = detectDesktopBuildType()
    val isDebug = buildType == DesktopBuildType.Debug

    val pkg = "com.project.analyzer.${spec.packageName ?: error("desktopBuildConfig: packageName is required")}"

    val fields = buildList {
        add(Field("String", "BUILD_TYPE", buildType.name.lowercase(Locale.US).asKotlinString()))
        add(Field("Boolean", "IS_DEBUG", isDebug.toString()))
        add(Field("String", "APP_NAME", (if (isDebug) "SimAnalyzer-debug" else "SimAnalyzer").asKotlinString()))
        add(Field("String", "VERSION_NAME", version.toString().asKotlinString()))

        addAll(spec.common.fields)
        addAll(if (isDebug) spec.debug.fields else spec.release.fields)
    }.distinctBy { it.name }

    val outDir = layout.buildDirectory
        .dir("generated/desktopBuildConfig/${buildType.name.lowercase(Locale.US)}/jvmMain/kotlin")
        .get()
        .asFile

    val genTask = tasks.register("generateDesktopBuildConfig") {
        inputs.property("buildType", buildType.name)
        inputs.property("packageName", pkg)
        inputs.property("fields", fields.joinToString("|") { "${it.type}:${it.name}=${it.valueLiteral}" })
        outputs.dir(outDir)

        doLast {
            val fileDir = outDir.resolve(pkg.replace('.', '/'))
            fileDir.mkdirs()

            val file = fileDir.resolve("BuildConfig.kt")
            file.writeText(
                buildString {
                    appendLine("package $pkg")
                    appendLine()
                    appendLine("/** Generated by Gradle. Do not edit manually. */")
                    appendLine("internal object BuildConfig {")
                    fields.forEach { f ->
                        appendLine("    internal const val ${f.name}: ${f.type} = ${f.valueLiteral}")
                    }
                    appendLine("}")
                }
            )
        }
    }

    extensions.configure<KotlinMultiplatformExtension> {
        sourceSets.getByName("jvmMain").kotlin.srcDir(outDir)
    }

    tasks.withType<KotlinCompile>().configureEach {
        val n = name.lowercase(Locale.US)
        val isJvmKotlinCompile =
            (n.startsWith("compile") && n.contains("kotlin") && n.contains("jvm"))

        if (isJvmKotlinCompile) {
            dependsOn(genTask)
        }
    }

    tasks.matching { t ->
        val n = t.name.lowercase(Locale.US)
        n.startsWith("ksp") && n.contains("kotlin") && n.contains("jvm")
    }.configureEach {
        dependsOn(genTask)
        inputs.dir(outDir)
    }
}

class DesktopBuildConfigSpec {

    var packageName: String? = null

    val common = Fields()
    val debug = Fields()
    val release = Fields()

    fun common(block: Fields.() -> Unit) = common.apply(block)
    fun debug(block: Fields.() -> Unit) = debug.apply(block)
    fun release(block: Fields.() -> Unit) = release.apply(block)
}

class Fields {

    internal val fields = mutableListOf<Field>()

    fun string(name: String, value: String) = fields.add(Field("String", name, value.asKotlinString()))
    fun boolean(name: String, value: Boolean) = fields.add(Field("Boolean", name, value.toString()))
    fun int(name: String, value: Int) = fields.add(Field("Int", name, value.toString()))
    fun long(name: String, value: Long) = fields.add(Field("Long", name, "${value}L"))
}

data class Field(
    val type: String,
    val name: String,
    val valueLiteral: String
)

enum class DesktopBuildType {
    Debug,
    Release
}

private fun Project.detectDesktopBuildType(): DesktopBuildType {
    providers.gradleProperty("buildType").orNull?.let { raw ->
        return if (raw.equals("release", ignoreCase = true)) DesktopBuildType.Release else DesktopBuildType.Debug
    }

    val tasks = gradle.startParameter.taskNames.joinToString(" ").lowercase(Locale.US)

    val looksLikeRelease = tasks.contains("release") || tasks.contains("package")
    return if (looksLikeRelease) DesktopBuildType.Release else DesktopBuildType.Debug
}

private fun String.asKotlinString(): String =
    buildString {
        append('"')
        for (ch in this@asKotlinString) {
            when (ch) {
                '\\' -> append("\\\\")
                '"' -> append("\\\"")
                '\n' -> append("\\n")
                '\r' -> append("\\r")
                '\t' -> append("\\t")
                else -> append(ch)
            }
        }
        append('"')
    }
