package com.project.analyzer.kmp

import org.gradle.api.Project
import org.gradle.kotlin.dsl.configure
import org.gradle.kotlin.dsl.withType
import org.jetbrains.kotlin.gradle.dsl.KotlinMultiplatformExtension
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile
import java.util.Locale

internal fun Project.configureDesktopBuildConfig(
    spec: DesktopBuildConfigSpec
) {
    val buildType = detectDesktopBuildType()
    val pkg = "com.project.analyzer.${spec.packageName ?: error("desktopBuildConfig: packageName is required")}"
    val fields = desktopBuildConfigFields(buildType, spec)

    val outDir = layout.buildDirectory
        .dir("generated/desktopBuildConfig/${buildType.name.lowercase(Locale.US)}/jvmMain/kotlin")
        .get()
        .asFile

    val genTask = tasks.register("generateDesktopBuildConfig") {
        inputs.property("buildType", buildType.name)
        inputs.property("packageName", pkg)
        inputs.property("fields", fields.joinToString("|") { "${it.type}:${it.name}=${it.valueLiteral}" })
        outputs.dir(outDir)

        doLast {
            val fileDir = outDir.resolve(pkg.replace('.', '/'))
            fileDir.mkdirs()

            val file = fileDir.resolve("BuildConfig.kt")
            file.writeText(
                buildString {
                    appendLine("package $pkg")
                    appendLine()
                    appendLine("/** Generated by Gradle. Do not edit manually. */")
                    appendLine("internal object BuildConfig {")
                    fields.forEach { f ->
                        appendLine("    internal const val ${f.name}: ${f.type} = ${f.valueLiteral}")
                    }
                    appendLine("}")
                }
            )
        }
    }

    extensions.configure<KotlinMultiplatformExtension> {
        sourceSets.getByName("jvmMain").kotlin.srcDir(outDir)
    }

    tasks.withType<KotlinCompile>().configureEach {
        val n = name.lowercase(Locale.US)
        val isJvmKotlinCompile =
            (n.startsWith("compile") && n.contains("kotlin") && n.contains("jvm"))

        if (isJvmKotlinCompile) {
            dependsOn(genTask)
        }
    }

    tasks.matching { t ->
        val n = t.name.lowercase(Locale.US)
        n.startsWith("ksp") && n.contains("kotlin") && n.contains("jvm")
    }.configureEach {
        dependsOn(genTask)
        inputs.dir(outDir)
    }
}

internal class DesktopBuildConfigSpec {

    var packageName: String? = null

    val common = Fields()
    val debug = Fields()
    val release = Fields()

    fun common(block: Fields.() -> Unit) = common.apply(block)
    fun debug(block: Fields.() -> Unit) = debug.apply(block)
    fun release(block: Fields.() -> Unit) = release.apply(block)
}

internal class Fields {

    internal val entries = mutableListOf<Field>()

    fun string(name: String, value: String) = entries.add(Field("String", name, value.asKotlinString()))
    fun boolean(name: String, value: Boolean) = entries.add(Field("Boolean", name, value.toString()))
    fun int(name: String, value: Int) = entries.add(Field("Int", name, value.toString()))
    fun long(name: String, value: Long) = entries.add(Field("Long", name, "${value}L"))
}

internal data class Field(
    val type: String,
    val name: String,
    val valueLiteral: String
)

internal enum class DesktopBuildType {
    Debug,
    Release
}

private fun Project.detectDesktopBuildType(): DesktopBuildType {
    providers.gradleProperty("buildType").orNull?.let { raw ->
        return if (raw.equals("release", ignoreCase = true)) DesktopBuildType.Release else DesktopBuildType.Debug
    }

    val tasks = gradle.startParameter.taskNames.joinToString(" ").lowercase(Locale.US)

    val looksLikeRelease = tasks.contains("release") || tasks.contains("package")
    return if (looksLikeRelease) DesktopBuildType.Release else DesktopBuildType.Debug
}

private fun Project.detectPortableFlag(): Boolean {
    providers.gradleProperty("isPortable").orNull?.toBoolean()?.let { return it }
    providers.gradleProperty("portable").orNull?.toBoolean()?.let { return it }

    System.getenv("IS_PORTABLE")?.toBoolean()?.let { return it }
    System.getenv("PORTABLE")?.toBoolean()?.let { return it }

    return false
}

private fun String.asKotlinString(): String =
    buildString {
        append('"')
        for (ch in this@asKotlinString) {
            when (ch) {
                '\\' -> append("\\\\")
                '"' -> append("\\\"")
                '\n' -> append("\\n")
                '\r' -> append("\\r")
                '\t' -> append("\\t")
                else -> append(ch)
            }
        }
        append('"')
    }

private fun Project.appDisplayVersion(): String =
    rootProject.extensions.extraProperties["appVersionDisplay"] as? String
        ?: version.toString()

private fun Project.appVersionBase(): String =
    rootProject.extensions.extraProperties["appVersionBase"] as? String
        ?: error("appVersionBase is not configured")

private fun Project.appVersionBuild(): Int =
    rootProject.extensions.extraProperties["appVersionBuild"] as? Int
        ?: error("appVersionBuild is not configured")

private fun Project.appVersionChannel(): String =
    rootProject.extensions.extraProperties["appVersionChannel"] as? String
        ?: error("appVersionChannel is not configured")

private fun Project.desktopBuildConfigFields(
    buildType: DesktopBuildType,
    spec: DesktopBuildConfigSpec,
): List<Field> {
    val isDebug = buildType == DesktopBuildType.Debug
    val selectedBuildFields = if (isDebug) spec.debug.entries else spec.release.entries

    return buildList {
        val versionChannel = appVersionChannel()
        add(Field("String", "BUILD_TYPE", buildType.name.lowercase(Locale.US).asKotlinString()))
        add(Field("Boolean", "IS_DEBUG", isDebug.toString()))
        add(Field("Boolean", "IS_PORTABLE", detectPortableFlag().toString()))
        add(Field("String", "APP_NAME", (if (isDebug) "SimAnalyzer-debug" else "SimAnalyzer").asKotlinString()))
        add(Field("String", "VERSION_BASE", appVersionBase().asKotlinString()))
        add(Field("Int", "VERSION_BUILD", appVersionBuild().toString()))
        add(Field("String", "VERSION_CHANNEL", versionChannel.asKotlinString()))
        add(Field("Boolean", "IS_DEV_VERSION", (versionChannel == "dev").toString()))
        add(Field("String", "VERSION_NAME", appDisplayVersion().asKotlinString()))
        addAll(spec.common.entries)
        addAll(selectedBuildFields)
    }.distinctBy(Field::name)
}
