config:
  validation: true
  warningsAsErrors: false

complexity:
  LongMethod:
    active: true
    allowedLines: 30
    ignoreAnnotated:
      - 'Composable'
      - 'Preview'

  LargeClass:
    active: true
    allowedLines: 400

  TooManyFunctions:
    active: true
    allowedFunctionsPerFile: 25
    allowedFunctionsPerClass: 20
    allowedFunctionsPerInterface: 20
    allowedFunctionsPerObject: 20
    allowedFunctionsPerEnum: 20
    ignoreDeprecated: true
    ignorePrivate: false
    ignoreInternal: false
    ignoreOverridden: true
    ignoreAnnotatedFunctions:
      - 'Preview'

  LongParameterList:
    active: true
    allowedFunctionParameters: 8
    allowedConstructorParameters: 7
    ignoreDefaultParameters: true
    ignoreDataClasses: true
    ignoreAnnotatedParameter:
      - 'Composable'
    ignoreFunction:
      - 'Composable'

  NestedBlockDepth:
    active: true
    allowedDepth: 4

  ComplexCondition:
    active: true
    allowedConditions: 4

style:
  MagicNumber:
    active: true
    excludes:
      - '**/test/**'
      - '**/androidTest/**'
      - '**/commonTest/**'
      - '**/*.kts'
    ignoreNumbers:
      - '-1'
      - '0'
      - '1'
      - '2'
    ignoreHashCodeFunction: true
    ignorePropertyDeclaration: false
    ignoreLocalVariableDeclaration: false
    ignoreConstantDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
    ignoreAnnotation: false
    ignoreNamedArgument: true
    ignoreEnums: false
    ignoreRanges: false
    ignoreExtensionFunctions: true

  MaxLineLength:
    active: true
    maxLineLength: 120
    excludePackageStatements: true
    excludeImportStatements: true
    excludeCommentStatements: false
    excludeRawStrings: true

  ReturnCount:
    active: true
    max: 3
    excludedFunctions:
      - 'equals'
    excludeLabeled: false
    excludeReturnFromLambda: true
    excludeGuardClauses: false

  ForbiddenComment:
    active: true

naming:
  ClassNaming:
    active: true
    classPattern: '[A-Z][a-zA-Z0-9]*'

  FunctionNaming:
    active: true
    excludes:
      - '**/test/**'
      - '**/androidTest/**'
      - '**/commonTest/**'
    functionPattern: '[a-zA-Z][a-zA-Z0-9]*'
    excludeClassPattern: '$^'
    ignoreAnnotated:
      - 'Composable'

  VariableNaming:
    active: true
    variablePattern: '[a-z][A-Za-z0-9]*'
    privateVariablePattern: '(_)?[a-z][A-Za-z0-9]*'
    excludeClassPattern: '$^'

  TopLevelPropertyNaming:
    active: true
    constantPattern: '_?[A-Z][_A-Za-z0-9]*'
    propertyPattern: '_?[A-Za-z][_A-Za-z0-9]*'
    privatePropertyPattern: '_?[A-Za-z][_A-Za-z0-9]*'

  PackageNaming:
    active: true
    packagePattern: '^[a-z]+(\.[a-z][A-Za-z0-9]*)*$'
