config:
  validation: true
  warningsAsErrors: false
  checkExhaustiveness: false
  excludes: [ ]

processors:
  active: true
  exclude:
    - 'DetektProgressListener'

console-reports:
  active: true
  exclude:
    - 'ProjectStatisticsReport'
    - 'ComplexityReport'
    - 'NotificationReport'
    - 'IssuesReport'
    - 'FileBasedIssuesReport'

comments:
  active: true
  UndocumentedPublicClass:
    active: false
  UndocumentedPublicFunction:
    active: false
  UndocumentedPublicProperty:
    active: false

complexity:
  active: true
  ComplexCondition:
    active: true
    allowedConditions: 7
  CyclomaticComplexMethod:
    active: true
    allowedComplexity: 40
    ignoreAnnotated:
      - "Composable"
  LargeClass:
    active: true
    allowedLines: 600
  LongMethod:
    active: true
    allowedLines: 200
    ignoreAnnotated:
      - "Composable"
  LongParameterList:
    active: true
    allowedFunctionParameters: 10
    allowedConstructorParameters: 10
    ignoreDefaultParameters: true
    ignoreDataClasses: true
    ignoreAnnotated:
      - "Composable"
  NestedBlockDepth:
    active: true
    allowedDepth: 6
  TooManyFunctions:
    active: false

coroutines:
  active: true
  GlobalCoroutineUsage:
    active: true
  RedundantSuspendModifier:
    active: true
  SleepInsteadOfDelay:
    active: true

empty-blocks:
  active: true

exceptions:
  active: true
  PrintStackTrace:
    active: true
  SwallowedException:
    active: false
    ignoredExceptionTypes:
      - 'InterruptedException'
      - 'MalformedURLException'
      - 'NumberFormatException'
      - 'ParseException'
      - 'IOException'
    allowedExceptionNameRegex: '_|(ignore|expected).*'
  TooGenericExceptionCaught:
    active: true
    exceptionNames:
      - 'ArrayIndexOutOfBoundsException'
      - 'Error'
      - 'IllegalMonitorStateException'
      - 'IndexOutOfBoundsException'
      - 'NullPointerException'
    allowedExceptionNameRegex: '_|(ignore|expected).*'

naming:
  active: true
  ClassNaming:
    active: true
    classPattern: '[A-Z][a-zA-Z0-9]*'
  ConstructorParameterNaming:
    active: true
    parameterPattern: '[a-z][A-Za-z0-9]*'
  EnumNaming:
    active: true
    enumEntryPattern: '[A-Z][_a-zA-Z0-9]*'
  FunctionNaming:
    active: true
    functionPattern: '[a-z][a-zA-Z0-9]*|[A-Z][a-zA-Z0-9]*'
  FunctionParameterNaming:
    active: true
    parameterPattern: '[a-z][A-Za-z0-9]*'
  InvalidPackageDeclaration:
    active: true
  MatchingDeclarationName:
    active: false
  ObjectPropertyNaming:
    active: true
    constantPattern: '[A-Za-z][_A-Za-z0-9]*'
    propertyPattern: '[A-Za-z][_A-Za-z0-9]*'
  PackageNaming:
    active: true
    packagePattern: '[a-z]+(\.[a-z][A-Za-z0-9]*)*'
  TopLevelPropertyNaming:
    active: true
    constantPattern: '[A-Z][_A-Z0-9]*|[a-z][A-Za-z0-9]*'
  VariableNaming:
    active: true
    variablePattern: '[a-z][A-Za-z0-9]*'

style:
  active: true
  CanBeNonNullable:
    active: true
  EqualsNullCall:
    active: true
  ForbiddenComment:
    active: true
    comments:
      - reason: 'Forbidden FIXME todo marker in comment'
        value: 'FIXME:'
      - reason: 'Forbidden STOPSHIP todo marker in comment'
        value: 'STOPSHIP:'
  ForbiddenVoid:
    active: true
  MagicNumber:
    active: false
  MaxLineLength:
    active: false
    maxLineLength: 120
  ModifierOrder:
    active: true
    autoCorrect: true
  OptionalUnit:
    active: true
    autoCorrect: true
  ReturnCount:
    active: false
    max: 6
    excludedFunctions:
      - 'equals'
    excludeLabeled: false
    excludeReturnFromLambda: true
    excludeGuardClauses: true
  ThrowsCount:
    active: false
  LoopWithTooManyJumpStatements:
    active: false
  UnnecessaryApply:
    active: true
    autoCorrect: true
  UnnecessaryInheritance:
    active: true
    autoCorrect: true
  UnusedImport:
    active: true
    autoCorrect: true
  UnusedPrivateClass:
    active: true
    excludes:
      - '**/di/**'
      - '**/*Bindings.kt'
      - '**/*Graph.kt'
      - '**/*Component.kt'
      - '**/*Module.kt'
      - '**/*Entry.kt'
      - '**/Qualifiers.kt'
  UnusedPrivateFunction:
    active: true
    allowedNames: '.*Preview$'
    excludes:
      - '**/di/**'
      - '**/*Bindings.kt'
      - '**/*Graph.kt'
      - '**/*Component.kt'
      - '**/*Module.kt'
      - '**/*Entry.kt'
      - '**/Qualifiers.kt'
  UnusedPrivateProperty:
    active: true
    excludes:
      - '**/di/**'
      - '**/*Bindings.kt'
      - '**/*Graph.kt'
      - '**/*Component.kt'
      - '**/*Module.kt'
      - '**/*Entry.kt'
      - '**/Qualifiers.kt'
  VarCouldBeVal:
    active: true
    autoCorrect: true
  WildcardImport:
    active: true
    excludeImports:
      - 'kotlinx.android.synthetic.*'

ktlint:
  active: true
  code_style: 'intellij_idea'
  autoCorrect: true
  AnnotationOnSeparateLine:
    active: true
  AnnotationSpacing:
    active: true
  ArgumentListWrapping:
    active: true
  BackingPropertyNaming:
    active: false
  BlockCommentInitialStarAlignment:
    active: true
  ChainWrapping:
    active: true
  CommentSpacing:
    active: true
  CommentWrapping:
    active: true
  ConditionWrapping:
    active: true
  ContextReceiverListWrapping:
    active: true
  SpacingAroundCurly:
    active: true
  SpacingAroundDoubleColon:
    active: true
  EnumEntryNameCase:
    active: true
  EnumWrapping:
    active: true
  Filename:
    active: false
  FinalNewline:
    active: true
  FunKeywordSpacing:
    active: true
  FunctionReturnTypeSpacing:
    active: true
  FunctionStartOfBodySpacing:
    active: true
  FunctionTypeReferenceSpacing:
    active: true
  IfElseBracing:
    active: true
  IfElseWrapping:
    active: true
  ImportOrdering:
    active: true
  Indentation:
    active: true
  KdocWrapping:
    active: true
  MaximumLineLength:
    active: false
    maxLineLength: 120
  ModifierListSpacing:
    active: true
  ModifierOrdering:
    active: true
  MultilineExpressionWrapping:
    active: false
  NoBlankLineBeforeRbrace:
    active: true
  NoBlankLinesInChainedMethodCalls:
    active: true
  NoConsecutiveBlankLines:
    active: true
  NoEmptyClassBody:
    active: true
  NoEmptyFirstLineInClassBody:
    active: false
  NoEmptyFirstLineInMethodBlock:
    active: true
  NoLineBreakAfterElse:
    active: true
  NoLineBreakBeforeAssignment:
    active: true
  NoMultipleSpaces:
    active: true
  NoSemicolons:
    active: true
  NoTrailingSpaces:
    active: true
  NoUnitReturn:
    active: true
  NoUnusedImports:
    active: true
  NoWildcardImports:
    active: true
  NullableTypeSpacing:
    active: true
  PackageName:
    active: true
  ParameterListSpacing:
    active: true
  ParameterListWrapping:
    active: true
  ParameterWrapping:
    active: true
  PropertyName:
    active: false
  PropertyWrapping:
    active: false
  SpacingAroundRangeOperator:
    active: true
  SpacingAroundAngleBrackets:
    active: true
  SpacingAroundColon:
    active: true
  SpacingAroundComma:
    active: true
  SpacingAroundDot:
    active: true
  SpacingAroundKeyword:
    active: true
  SpacingAroundOperators:
    active: true
  SpacingAroundParens:
    active: true
  SpacingAroundUnaryOperator:
    active: true
  SpacingBetweenDeclarationsWithAnnotations:
    active: true
  SpacingBetweenDeclarationsWithComments:
    active: true
  SpacingBetweenFunctionNameAndOpeningParenthesis:
    active: true
  StringTemplate:
    active: true
  StringTemplateIndent:
    active: true
  TrailingCommaOnCallSite:
    active: true
  TrailingCommaOnDeclarationSite:
    active: true
  TryCatchFinallySpacing:
    active: true
  TypeArgumentListSpacing:
    active: true
  TypeParameterListSpacing:
    active: true
  UnnecessaryParenthesesBeforeTrailingLambda:
    active: true
  Wrapping:
    active: true
