package com.project.analyzer.telemetry.recording.api.session

public data class RecordedTelemetryPayload(
    val gameId: String,
    val carModel: String? = null,
    val carLabel: String? = null,
    val trackLabel: String? = null,
    val trackLayoutLabel: String? = null,
    val vehicleClassHint: String? = null,
    val sessionTypeLabel: String? = null,
    val sessionPhaseLabel: String? = null,
    val tyreCompoundLabel: String? = null,
    val isRainTyres: Boolean? = null,
    val lapNumber: Int? = null,
    val completedLaps: Int? = null,
    val currentLapTimeMs: Int? = null,
    val lastLapTimeMs: Int? = null,
    val bestLapTimeMs: Int? = null,
    val estimatedLapTimeMs: Int? = null,
    val currentSectorIndex: Int? = null,
    val lastSectorTimeMs: Int? = null,
    val isLapValid: Boolean? = null,
    val speedKmh: Float? = null,
    val gear: Int? = null,
    val rpm: Float? = null,
    val throttle: Float? = null,
    val brake: Float? = null,
    val steeringAngleRad: Float? = null,
    val lateralG: Float? = null,
    val yawRateRad: Float? = null,
    val fuelLiters: Float? = null,
    val fuelCapacityLiters: Float? = null,
    val fuelPerLapLiters: Float? = null,
    val airTempC: Float? = null,
    val roadTempC: Float? = null,
    val brakeBias: Float? = null,
    val tcLevel: Int? = null,
    val absLevel: Int? = null,
    val pitLimiterOn: Boolean? = null,
    val tyreFl: RecordedTelemetryTyreSnapshot? = null,
    val tyreFr: RecordedTelemetryTyreSnapshot? = null,
    val tyreRl: RecordedTelemetryTyreSnapshot? = null,
    val tyreRr: RecordedTelemetryTyreSnapshot? = null,
)
